version: '3'
services:
  backend:
    container_name: backend
    build: ./backend/
    restart: always
    ports:
      - "8080:8080"
    environment:
      - VITE_DB_HOST=postgres
      - VITE_IP_ADDR=0.0.0.0
      - VITE_PORT=8080
      - VITE_LOGS_DIR=logs/
      - VITE_DB_PORT=5432
      - VITE_DB_USER=rajashree
      - VITE_DB_PASS=rajashree
      - VITE_DB_NAME=psu_foodcarts
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    build: ./frontend/
    restart: always
    ports:
      - "88:80" # We need to map here for convenience, so we don't conflict with a potential possible local server
    environment:
      - VITE_BACKEND_IP=backend
      - VITE_BACKEND_PORT=8080
      - VITE_MICROSERVICE_IP=127.0.0.1
      - VITE_MICROSERVICE_PORT=80

  microservice:
    container_name: microservice
    build: ./microservice/
    restart: always
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgres://rajashree:rajashree@postgres:5432/psu_foodcarts
    depends_on: #This is a lie
      - postgres
  
  postgres:
    container_name: psu_foodcarts
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432" 
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=rajashree
      - POSTGRES_PASSWORD=rajashree
      - POSTGRES_DB=psu_foodcarts

volumes:
  db:
    driver: local
